### ISSUE TITLE
ZO_COMPACT_DATA_RETENTION_DAYS is being applied as int instead of string 

### ISSUE THREAD

**Issue by amitza** [mshade/openobserve-chart#11]
When trying to set the `ZO_COMPACT_DATA_RETENTION_DAYS` env var the result in the manifest is an int instead of string. 
This causes an issue when trying to install the chart:
```
json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string
```

The solution would be to quote each env var value using Helm's  `quote` function

**Comment by mshade** [comment]
Thanks for the feedback! I'll fix this bug.
